export const SITE = {
  name: "Gusto Kartepe",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.gustokartepe.com",
  description: "Doganin kalbinde, Kartepe ormanlarinda serpme kahvalti ve izgara restorani.",
  titleSuffix: "Gusto Kartepe | Doganin Icinde Serpme Kahvalti & Izgara",
  phone: "+90 532 419 92 93",
  email: "gustokartepe@gmail.com",
  address: {
    streetAddress: "Sirinsulhiye Mh. Degirmen Vadisi Sk. No: 14/1",
    addressLocality: "Kartepe",
    addressRegion: "Kocaeli",
    postalCode: "41180",
    addressCountry: "TR",
  },
  geo: { latitude: 40.7059, longitude: 29.7092 },
  openingHours: "Mo-Su 09:00-22:00",
  instagram: "https://www.instagram.com/gustokartepe",
  facebook: "",
  linkedin: "",
  youtube: "",
  tiktok: "",
};
